baseURL = "https://kabircampwala.github.io/"
languageCode = "en-us"
title = "Kabir Ahmed Campwala"
theme="archie"
copyright = ""
# Code Highlight
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

paginate=3 # articles per page

[params]
	mode="toggle" # color-mode → light,dark,toggle or auto
	useCDN=false # don't use CDNs for fonts and icons, instead serve them locally.
	subtitle = "[Technical Content Writer](https://mysqlcode.com/)"

# Social Tags  

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/KabirCampwala"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/KabirCampwala"

[[params.social]]
name = "LinkedIn"
icon = "linkedin"
url = "https://www.linkedin.com/in/kabircampwala/"

# Main menu Items

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4
