baseURL = "https://kabircampwala.github.io/"
title = "Kabir Campwala"
theme = "wisdom"

languageCode = "en-us"
enableRobotsTXT = true

googleAnalytics = 'G-HLB7LE4D83'

[params]
  latestPostsLimit = 30
  hideReadingTime = true
  hideAuthor = false

[menu]
[[menu.main]]
  identifier = 'home'
  name = 'Home'
  url = '/'
  weight = -110
